import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import { MenuIcon } from "lucide-react";
import { Crimson_Text } from "next/font/google";
import { IMAGES } from "@/assets";

const satoshi = localFont({
  src: "../assets/fonts/Satoshi-Variable.ttf",
  display: "swap",
  variable: "--font-satoshi",
});

const neue = localFont({
  src: "../assets/fonts/neue-gravica-bold.ttf",
  display: "swap",
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const crimsonText = Crimson_Text({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-crimson-text",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonText.variable} ${satoshi.className} ${neue.variable} antialiased bg-brand-bg`}
      >
        <main className="flex flex-col min-h-screen relative">
          <header className="flex items-center justify-between w-full ">
            <div className="fixed top-0 w-full p-4 flex items-center justify-between z-40 bg-brand-bg px-10">
              <Image
                src={IMAGES.logo}
                alt="logo"
                className="h-10 object-contain w-fit"
              />
              <MenuIcon />
            </div>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
